site_name: Nebula
theme: readthedocs
pages:
    - Home: index.md
    - Design:
      - Architecture: architecture.md
      - Internals: internals.md
    - Setting up:
      - Docker-compose localhost tutorial: getting-started.md
      - Installing: install.md
    - Configuring:
      - Using: use.md
      - Configuration settings: config.md
      - Scaling: scaling.md
    - Controling:
      - CLI: cli.md
      - API: api.md
      - SDK:
        - Python: 'sdk/python.md'
    - Misc:
      - What to monitor: monitoring.md
      - Nebula vs. Others: compare2orchestrators.md
      - Contributing: contribute.md
      - Where to get help: help.md
      - Release notes: release-notes.md
repo_url: https://github.com/nebula-orchestrator/docs
markdown_extensions:
  - admonition
