site_name: Nebula
theme: readthedocs
pages:
    - Home: index.md
    - Setting up:
      - Getting Started: getting-started.md
      - Installing: install.md
    - Configuring:
      - Using: use.md
      - Configuration settings: config.md
      - Scaling: scaling.md
    - Controling:
      - CLI: cli.md
      - API: api.md
      - SDK:
        - Python: 'sdk/python.md'
    - Misc:
      - What to monitor: monitoring.md
      - Roadmap: roadmap.md
      - Nebula vs. Others: compare2orchestrators.md
      - Contributing: contribute.md
repo_url: https://github.com/nebula-orchestrator/docs